/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.information_schema.tables;


import com.example.jooq.demo_jooq.introduction.db.information_schema.InformationSchema;
import com.example.jooq.demo_jooq.introduction.db.information_schema.tables.records._PgForeignDataWrappersRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _PgForeignDataWrappers extends TableImpl<_PgForeignDataWrappersRecord> {

    private static final long serialVersionUID = -224629566;

    /**
     * The reference instance of <code>information_schema._pg_foreign_data_wrappers</code>
     */
    public static final _PgForeignDataWrappers _PG_FOREIGN_DATA_WRAPPERS = new _PgForeignDataWrappers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<_PgForeignDataWrappersRecord> getRecordType() {
        return _PgForeignDataWrappersRecord.class;
    }

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.oid</code>.
     */
    public final TableField<_PgForeignDataWrappersRecord, Long> OID = createField(DSL.name("oid"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.fdwowner</code>.
     */
    public final TableField<_PgForeignDataWrappersRecord, Long> FDWOWNER = createField(DSL.name("fdwowner"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.fdwoptions</code>.
     */
    public final TableField<_PgForeignDataWrappersRecord, String[]> FDWOPTIONS = createField(DSL.name("fdwoptions"), org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.foreign_data_wrapper_catalog</code>.
     */
    public final TableField<_PgForeignDataWrappersRecord, String> FOREIGN_DATA_WRAPPER_CATALOG = createField(DSL.name("foreign_data_wrapper_catalog"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.foreign_data_wrapper_name</code>.
     */
    public final TableField<_PgForeignDataWrappersRecord, String> FOREIGN_DATA_WRAPPER_NAME = createField(DSL.name("foreign_data_wrapper_name"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.authorization_identifier</code>.
     */
    public final TableField<_PgForeignDataWrappersRecord, String> AUTHORIZATION_IDENTIFIER = createField(DSL.name("authorization_identifier"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema._pg_foreign_data_wrappers.foreign_data_wrapper_language</code>.
     */
    public final TableField<_PgForeignDataWrappersRecord, String> FOREIGN_DATA_WRAPPER_LANGUAGE = createField(DSL.name("foreign_data_wrapper_language"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>information_schema._pg_foreign_data_wrappers</code> table reference
     */
    public _PgForeignDataWrappers() {
        this(DSL.name("_pg_foreign_data_wrappers"), null);
    }

    /**
     * Create an aliased <code>information_schema._pg_foreign_data_wrappers</code> table reference
     */
    public _PgForeignDataWrappers(String alias) {
        this(DSL.name(alias), _PG_FOREIGN_DATA_WRAPPERS);
    }

    /**
     * Create an aliased <code>information_schema._pg_foreign_data_wrappers</code> table reference
     */
    public _PgForeignDataWrappers(Name alias) {
        this(alias, _PG_FOREIGN_DATA_WRAPPERS);
    }

    private _PgForeignDataWrappers(Name alias, Table<_PgForeignDataWrappersRecord> aliased) {
        this(alias, aliased, null);
    }

    private _PgForeignDataWrappers(Name alias, Table<_PgForeignDataWrappersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> _PgForeignDataWrappers(Table<O> child, ForeignKey<O, _PgForeignDataWrappersRecord> key) {
        super(child, key, _PG_FOREIGN_DATA_WRAPPERS);
    }

    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    @Override
    public _PgForeignDataWrappers as(String alias) {
        return new _PgForeignDataWrappers(DSL.name(alias), this);
    }

    @Override
    public _PgForeignDataWrappers as(Name alias) {
        return new _PgForeignDataWrappers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public _PgForeignDataWrappers rename(String name) {
        return new _PgForeignDataWrappers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public _PgForeignDataWrappers rename(Name name) {
        return new _PgForeignDataWrappers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String[], String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
