/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.routines;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsonbSet extends AbstractRoutine<JSONB> {

    private static final long serialVersionUID = 1765637068;

    /**
     * The parameter <code>pg_catalog.jsonb_set.RETURN_VALUE</code>.
     */
    public static final Parameter<JSONB> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.JSONB, false, false);

    /**
     * The parameter <code>pg_catalog.jsonb_set.jsonb_in</code>.
     */
    public static final Parameter<JSONB> JSONB_IN = Internal.createParameter("jsonb_in", org.jooq.impl.SQLDataType.JSONB, false, false);

    /**
     * The parameter <code>pg_catalog.jsonb_set.path</code>.
     */
    public static final Parameter<String[]> PATH = Internal.createParameter("path", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), false, false);

    /**
     * The parameter <code>pg_catalog.jsonb_set.replacement</code>.
     */
    public static final Parameter<JSONB> REPLACEMENT = Internal.createParameter("replacement", org.jooq.impl.SQLDataType.JSONB, false, false);

    /**
     * The parameter <code>pg_catalog.jsonb_set.create_if_missing</code>.
     */
    public static final Parameter<Boolean> CREATE_IF_MISSING = Internal.createParameter("create_if_missing", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), true, false);

    /**
     * Create a new routine call instance
     */
    public JsonbSet() {
        super("jsonb_set", PgCatalog.PG_CATALOG, org.jooq.impl.SQLDataType.JSONB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(JSONB_IN);
        addInParameter(PATH);
        addInParameter(REPLACEMENT);
        addInParameter(CREATE_IF_MISSING);
    }

    /**
     * Set the <code>jsonb_in</code> parameter IN value to the routine
     */
    public void setJsonbIn(JSONB value) {
        setValue(JSONB_IN, value);
    }

    /**
     * Set the <code>jsonb_in</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setJsonbIn(Field<JSONB> field) {
        setField(JSONB_IN, field);
    }

    /**
     * Set the <code>path</code> parameter IN value to the routine
     */
    public void setPath(String... value) {
        setValue(PATH, value);
    }

    /**
     * Set the <code>path</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setPath(Field<String[]> field) {
        setField(PATH, field);
    }

    /**
     * Set the <code>replacement</code> parameter IN value to the routine
     */
    public void setReplacement(JSONB value) {
        setValue(REPLACEMENT, value);
    }

    /**
     * Set the <code>replacement</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setReplacement(Field<JSONB> field) {
        setField(REPLACEMENT, field);
    }

    /**
     * Set the <code>create_if_missing</code> parameter IN value to the routine
     */
    public void setCreateIfMissing(Boolean value) {
        setValue(CREATE_IF_MISSING, value);
    }

    /**
     * Set the <code>create_if_missing</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setCreateIfMissing(Field<Boolean> field) {
        setField(CREATE_IF_MISSING, field);
    }
}
