/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.routines;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.PgCatalog;

import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatFile2 extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1801575593;

    /**
     * The parameter <code>pg_catalog.pg_stat_file.filename</code>.
     */
    public static final Parameter<String> FILENAME = Internal.createParameter("filename", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.missing_ok</code>.
     */
    public static final Parameter<Boolean> MISSING_OK = Internal.createParameter("missing_ok", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.size</code>.
     */
    public static final Parameter<Long> SIZE = Internal.createParameter("size", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.access</code>.
     */
    public static final Parameter<OffsetDateTime> ACCESS = Internal.createParameter("access", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.modification</code>.
     */
    public static final Parameter<OffsetDateTime> MODIFICATION = Internal.createParameter("modification", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.change</code>.
     */
    public static final Parameter<OffsetDateTime> CHANGE = Internal.createParameter("change", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.creation</code>.
     */
    public static final Parameter<OffsetDateTime> CREATION = Internal.createParameter("creation", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);

    /**
     * The parameter <code>pg_catalog.pg_stat_file.isdir</code>.
     */
    public static final Parameter<Boolean> ISDIR = Internal.createParameter("isdir", org.jooq.impl.SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public PgStatFile2() {
        super("pg_stat_file", PgCatalog.PG_CATALOG);

        addInParameter(FILENAME);
        addInParameter(MISSING_OK);
        addOutParameter(SIZE);
        addOutParameter(ACCESS);
        addOutParameter(MODIFICATION);
        addOutParameter(CHANGE);
        addOutParameter(CREATION);
        addOutParameter(ISDIR);
        setOverloaded(true);
    }

    /**
     * Set the <code>filename</code> parameter IN value to the routine
     */
    public void setFilename(String value) {
        setValue(FILENAME, value);
    }

    /**
     * Set the <code>missing_ok</code> parameter IN value to the routine
     */
    public void setMissingOk(Boolean value) {
        setValue(MISSING_OK, value);
    }

    /**
     * Get the <code>size</code> parameter OUT value from the routine
     */
    public Long getSize() {
        return get(SIZE);
    }

    /**
     * Get the <code>access</code> parameter OUT value from the routine
     */
    public OffsetDateTime getAccess() {
        return get(ACCESS);
    }

    /**
     * Get the <code>modification</code> parameter OUT value from the routine
     */
    public OffsetDateTime getModification() {
        return get(MODIFICATION);
    }

    /**
     * Get the <code>change</code> parameter OUT value from the routine
     */
    public OffsetDateTime getChange() {
        return get(CHANGE);
    }

    /**
     * Get the <code>creation</code> parameter OUT value from the routine
     */
    public OffsetDateTime getCreation() {
        return get(CREATION);
    }

    /**
     * Get the <code>isdir</code> parameter OUT value from the routine
     */
    public Boolean getIsdir() {
        return get(ISDIR);
    }
}
