/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.routines;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatReset extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1331691333;

    /**
     * Create a new routine call instance
     */
    public PgStatReset() {
        super("pg_stat_reset", PgCatalog.PG_CATALOG);
    }
}
