/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.Indexes;
import com.example.jooq.demo_jooq.introduction.db.pg_catalog.PgCatalog;
import com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.records.PgClassRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgClass extends TableImpl<PgClassRecord> {

    private static final long serialVersionUID = 19324220;

    /**
     * The reference instance of <code>pg_catalog.pg_class</code>
     */
    public static final PgClass PG_CLASS = new PgClass();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgClassRecord> getRecordType() {
        return PgClassRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_class.relname</code>.
     */
    public final TableField<PgClassRecord, String> RELNAME = createField(DSL.name("relname"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relnamespace</code>.
     */
    public final TableField<PgClassRecord, Long> RELNAMESPACE = createField(DSL.name("relnamespace"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.reltype</code>.
     */
    public final TableField<PgClassRecord, Long> RELTYPE = createField(DSL.name("reltype"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.reloftype</code>.
     */
    public final TableField<PgClassRecord, Long> RELOFTYPE = createField(DSL.name("reloftype"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relowner</code>.
     */
    public final TableField<PgClassRecord, Long> RELOWNER = createField(DSL.name("relowner"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relam</code>.
     */
    public final TableField<PgClassRecord, Long> RELAM = createField(DSL.name("relam"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relfilenode</code>.
     */
    public final TableField<PgClassRecord, Long> RELFILENODE = createField(DSL.name("relfilenode"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.reltablespace</code>.
     */
    public final TableField<PgClassRecord, Long> RELTABLESPACE = createField(DSL.name("reltablespace"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relpages</code>.
     */
    public final TableField<PgClassRecord, Integer> RELPAGES = createField(DSL.name("relpages"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.reltuples</code>.
     */
    public final TableField<PgClassRecord, Float> RELTUPLES = createField(DSL.name("reltuples"), org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relallvisible</code>.
     */
    public final TableField<PgClassRecord, Integer> RELALLVISIBLE = createField(DSL.name("relallvisible"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.reltoastrelid</code>.
     */
    public final TableField<PgClassRecord, Long> RELTOASTRELID = createField(DSL.name("reltoastrelid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relhasindex</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELHASINDEX = createField(DSL.name("relhasindex"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relisshared</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELISSHARED = createField(DSL.name("relisshared"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relpersistence</code>.
     */
    public final TableField<PgClassRecord, String> RELPERSISTENCE = createField(DSL.name("relpersistence"), org.jooq.impl.SQLDataType.CHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relkind</code>.
     */
    public final TableField<PgClassRecord, String> RELKIND = createField(DSL.name("relkind"), org.jooq.impl.SQLDataType.CHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relnatts</code>.
     */
    public final TableField<PgClassRecord, Short> RELNATTS = createField(DSL.name("relnatts"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relchecks</code>.
     */
    public final TableField<PgClassRecord, Short> RELCHECKS = createField(DSL.name("relchecks"), org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relhasoids</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELHASOIDS = createField(DSL.name("relhasoids"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relhaspkey</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELHASPKEY = createField(DSL.name("relhaspkey"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relhasrules</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELHASRULES = createField(DSL.name("relhasrules"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relhastriggers</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELHASTRIGGERS = createField(DSL.name("relhastriggers"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relhassubclass</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELHASSUBCLASS = createField(DSL.name("relhassubclass"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relrowsecurity</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELROWSECURITY = createField(DSL.name("relrowsecurity"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relforcerowsecurity</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELFORCEROWSECURITY = createField(DSL.name("relforcerowsecurity"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relispopulated</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELISPOPULATED = createField(DSL.name("relispopulated"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relreplident</code>.
     */
    public final TableField<PgClassRecord, String> RELREPLIDENT = createField(DSL.name("relreplident"), org.jooq.impl.SQLDataType.CHAR.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relispartition</code>.
     */
    public final TableField<PgClassRecord, Boolean> RELISPARTITION = createField(DSL.name("relispartition"), org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relfrozenxid</code>.
     */
    public final TableField<PgClassRecord, Long> RELFROZENXID = createField(DSL.name("relfrozenxid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relminmxid</code>.
     */
    public final TableField<PgClassRecord, Long> RELMINMXID = createField(DSL.name("relminmxid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_class.relacl</code>.
     */
    public final TableField<PgClassRecord, String[]> RELACL = createField(DSL.name("relacl"), org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>pg_catalog.pg_class.reloptions</code>.
     */
    public final TableField<PgClassRecord, String[]> RELOPTIONS = createField(DSL.name("reloptions"), org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PgClassRecord, Object> RELPARTBOUND = createField(DSL.name("relpartbound"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"pg_node_tree\""), this, "");

    /**
     * Create a <code>pg_catalog.pg_class</code> table reference
     */
    public PgClass() {
        this(DSL.name("pg_class"), null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_class</code> table reference
     */
    public PgClass(String alias) {
        this(DSL.name(alias), PG_CLASS);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_class</code> table reference
     */
    public PgClass(Name alias) {
        this(alias, PG_CLASS);
    }

    private PgClass(Name alias, Table<PgClassRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgClass(Name alias, Table<PgClassRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PgClass(Table<O> child, ForeignKey<O, PgClassRecord> key) {
        super(child, key, PG_CLASS);
    }

    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PG_CLASS_RELNAME_NSP_INDEX, Indexes.PG_CLASS_TBLSPC_RELFILENODE_INDEX);
    }

    @Override
    public PgClass as(String alias) {
        return new PgClass(DSL.name(alias), this);
    }

    @Override
    public PgClass as(Name alias) {
        return new PgClass(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PgClass rename(String name) {
        return new PgClass(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgClass rename(Name name) {
        return new PgClass(name, null);
    }
}
