/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.Indexes;
import com.example.jooq.demo_jooq.introduction.db.pg_catalog.PgCatalog;
import com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.records.PgDependRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgDepend extends TableImpl<PgDependRecord> {

    private static final long serialVersionUID = -961915086;

    /**
     * The reference instance of <code>pg_catalog.pg_depend</code>
     */
    public static final PgDepend PG_DEPEND = new PgDepend();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgDependRecord> getRecordType() {
        return PgDependRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_depend.classid</code>.
     */
    public final TableField<PgDependRecord, Long> CLASSID = createField(DSL.name("classid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_depend.objid</code>.
     */
    public final TableField<PgDependRecord, Long> OBJID = createField(DSL.name("objid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_depend.objsubid</code>.
     */
    public final TableField<PgDependRecord, Integer> OBJSUBID = createField(DSL.name("objsubid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_depend.refclassid</code>.
     */
    public final TableField<PgDependRecord, Long> REFCLASSID = createField(DSL.name("refclassid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_depend.refobjid</code>.
     */
    public final TableField<PgDependRecord, Long> REFOBJID = createField(DSL.name("refobjid"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_depend.refobjsubid</code>.
     */
    public final TableField<PgDependRecord, Integer> REFOBJSUBID = createField(DSL.name("refobjsubid"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_depend.deptype</code>.
     */
    public final TableField<PgDependRecord, String> DEPTYPE = createField(DSL.name("deptype"), org.jooq.impl.SQLDataType.CHAR.nullable(false), this, "");

    /**
     * Create a <code>pg_catalog.pg_depend</code> table reference
     */
    public PgDepend() {
        this(DSL.name("pg_depend"), null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_depend</code> table reference
     */
    public PgDepend(String alias) {
        this(DSL.name(alias), PG_DEPEND);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_depend</code> table reference
     */
    public PgDepend(Name alias) {
        this(alias, PG_DEPEND);
    }

    private PgDepend(Name alias, Table<PgDependRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgDepend(Name alias, Table<PgDependRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PgDepend(Table<O> child, ForeignKey<O, PgDependRecord> key) {
        super(child, key, PG_DEPEND);
    }

    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PG_DEPEND_DEPENDER_INDEX, Indexes.PG_DEPEND_REFERENCE_INDEX);
    }

    @Override
    public PgDepend as(String alias) {
        return new PgDepend(DSL.name(alias), this);
    }

    @Override
    public PgDepend as(Name alias) {
        return new PgDepend(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PgDepend rename(String name) {
        return new PgDepend(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgDepend rename(Name name) {
        return new PgDepend(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Integer, Long, Long, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
