/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.Indexes;
import com.example.jooq.demo_jooq.introduction.db.pg_catalog.PgCatalog;
import com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.records.PgUserMappingRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgUserMapping extends TableImpl<PgUserMappingRecord> {

    private static final long serialVersionUID = 604376655;

    /**
     * The reference instance of <code>pg_catalog.pg_user_mapping</code>
     */
    public static final PgUserMapping PG_USER_MAPPING = new PgUserMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgUserMappingRecord> getRecordType() {
        return PgUserMappingRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_user_mapping.umuser</code>.
     */
    public final TableField<PgUserMappingRecord, Long> UMUSER = createField(DSL.name("umuser"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_user_mapping.umserver</code>.
     */
    public final TableField<PgUserMappingRecord, Long> UMSERVER = createField(DSL.name("umserver"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pg_catalog.pg_user_mapping.umoptions</code>.
     */
    public final TableField<PgUserMappingRecord, String[]> UMOPTIONS = createField(DSL.name("umoptions"), org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * Create a <code>pg_catalog.pg_user_mapping</code> table reference
     */
    public PgUserMapping() {
        this(DSL.name("pg_user_mapping"), null);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_user_mapping</code> table reference
     */
    public PgUserMapping(String alias) {
        this(DSL.name(alias), PG_USER_MAPPING);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_user_mapping</code> table reference
     */
    public PgUserMapping(Name alias) {
        this(alias, PG_USER_MAPPING);
    }

    private PgUserMapping(Name alias, Table<PgUserMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private PgUserMapping(Name alias, Table<PgUserMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PgUserMapping(Table<O> child, ForeignKey<O, PgUserMappingRecord> key) {
        super(child, key, PG_USER_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return PgCatalog.PG_CATALOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PG_USER_MAPPING_USER_SERVER_INDEX);
    }

    @Override
    public PgUserMapping as(String alias) {
        return new PgUserMapping(DSL.name(alias), this);
    }

    @Override
    public PgUserMapping as(Name alias) {
        return new PgUserMapping(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PgUserMapping rename(String name) {
        return new PgUserMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgUserMapping rename(Name name) {
        return new PgUserMapping(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
