/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.public_.tables.records;


import com.example.jooq.demo_jooq.introduction.db.public_.tables.Employee;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> implements Record6<Integer, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1150389394;

    /**
     * Setter for <code>public.Employee.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Employee.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Employee.surname</code>.
     */
    public void setSurname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Employee.surname</code>.
     */
    public String getSurname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.Employee.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Employee.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.Employee.patronymic</code>.
     */
    public void setPatronymic(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.Employee.patronymic</code>.
     */
    public String getPatronymic() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.Employee.organization_id</code>.
     */
    public void setOrganizationId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.Employee.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.Employee.supervisor_id</code>.
     */
    public void setSupervisorId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.Employee.supervisor_id</code>.
     */
    public Integer getSupervisorId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Employee.EMPLOYEE.ID;
    }

    @Override
    public Field<String> field2() {
        return Employee.EMPLOYEE.SURNAME;
    }

    @Override
    public Field<String> field3() {
        return Employee.EMPLOYEE.NAME;
    }

    @Override
    public Field<String> field4() {
        return Employee.EMPLOYEE.PATRONYMIC;
    }

    @Override
    public Field<Integer> field5() {
        return Employee.EMPLOYEE.ORGANIZATION_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Employee.EMPLOYEE.SUPERVISOR_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSurname();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getPatronymic();
    }

    @Override
    public Integer component5() {
        return getOrganizationId();
    }

    @Override
    public Integer component6() {
        return getSupervisorId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSurname();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getPatronymic();
    }

    @Override
    public Integer value5() {
        return getOrganizationId();
    }

    @Override
    public Integer value6() {
        return getSupervisorId();
    }

    @Override
    public EmployeeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EmployeeRecord value2(String value) {
        setSurname(value);
        return this;
    }

    @Override
    public EmployeeRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public EmployeeRecord value4(String value) {
        setPatronymic(value);
        return this;
    }

    @Override
    public EmployeeRecord value5(Integer value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public EmployeeRecord value6(Integer value) {
        setSupervisorId(value);
        return this;
    }

    @Override
    public EmployeeRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(Integer id, String surname, String name, String patronymic, Integer organizationId, Integer supervisorId) {
        super(Employee.EMPLOYEE);

        set(0, id);
        set(1, surname);
        set(2, name);
        set(3, patronymic);
        set(4, organizationId);
        set(5, supervisorId);
    }
}
