/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.public_;


import com.example.jooq.demo_jooq.introduction.db.public_.tables.Employee;
import com.example.jooq.demo_jooq.introduction.db.public_.tables.Organization;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EMPLOYEE_PK = Indexes0.EMPLOYEE_PK;
    public static final Index ORGANIZATION_PK = Indexes0.ORGANIZATION_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EMPLOYEE_PK = Internal.createIndex("employee_pk", Employee.EMPLOYEE, new OrderField[] { Employee.EMPLOYEE.ID }, true);
        public static Index ORGANIZATION_PK = Internal.createIndex("organization_pk", Organization.ORGANIZATION, new OrderField[] { Organization.ORGANIZATION.ID }, true);
    }
}
