/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.public_;


import com.example.jooq.demo_jooq.introduction.db.public_.tables.Employee;
import com.example.jooq.demo_jooq.introduction.db.public_.tables.Organization;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>public.Organization</code>.
     */
    public static final Organization ORGANIZATION = Organization.ORGANIZATION;
}
