/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.records;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.PgDbRoleSetting;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgDbRoleSettingRecord extends TableRecordImpl<PgDbRoleSettingRecord> implements Record3<Long, Long, String[]> {

    private static final long serialVersionUID = 1083244205;

    /**
     * Setter for <code>pg_catalog.pg_db_role_setting.setdatabase</code>.
     */
    public void setSetdatabase(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_db_role_setting.setdatabase</code>.
     */
    public Long getSetdatabase() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_db_role_setting.setrole</code>.
     */
    public void setSetrole(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_db_role_setting.setrole</code>.
     */
    public Long getSetrole() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_db_role_setting.setconfig</code>.
     */
    public void setSetconfig(String... value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_db_role_setting.setconfig</code>.
     */
    public String[] getSetconfig() {
        return (String[]) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String[]> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgDbRoleSetting.PG_DB_ROLE_SETTING.SETDATABASE;
    }

    @Override
    public Field<Long> field2() {
        return PgDbRoleSetting.PG_DB_ROLE_SETTING.SETROLE;
    }

    @Override
    public Field<String[]> field3() {
        return PgDbRoleSetting.PG_DB_ROLE_SETTING.SETCONFIG;
    }

    @Override
    public Long component1() {
        return getSetdatabase();
    }

    @Override
    public Long component2() {
        return getSetrole();
    }

    @Override
    public String[] component3() {
        return getSetconfig();
    }

    @Override
    public Long value1() {
        return getSetdatabase();
    }

    @Override
    public Long value2() {
        return getSetrole();
    }

    @Override
    public String[] value3() {
        return getSetconfig();
    }

    @Override
    public PgDbRoleSettingRecord value1(Long value) {
        setSetdatabase(value);
        return this;
    }

    @Override
    public PgDbRoleSettingRecord value2(Long value) {
        setSetrole(value);
        return this;
    }

    @Override
    public PgDbRoleSettingRecord value3(String... value) {
        setSetconfig(value);
        return this;
    }

    @Override
    public PgDbRoleSettingRecord values(Long value1, Long value2, String[] value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgDbRoleSettingRecord
     */
    public PgDbRoleSettingRecord() {
        super(PgDbRoleSetting.PG_DB_ROLE_SETTING);
    }

    /**
     * Create a detached, initialised PgDbRoleSettingRecord
     */
    public PgDbRoleSettingRecord(Long setdatabase, Long setrole, String[] setconfig) {
        super(PgDbRoleSetting.PG_DB_ROLE_SETTING);

        set(0, setdatabase);
        set(1, setrole);
        set(2, setconfig);
    }
}
