/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.records;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.PgGetKeywords;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgGetKeywordsRecord extends TableRecordImpl<PgGetKeywordsRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 498317994;

    /**
     * Setter for <code>pg_catalog.pg_get_keywords.word</code>.
     */
    public void setWord(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_get_keywords.word</code>.
     */
    public String getWord() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_get_keywords.catcode</code>.
     */
    public void setCatcode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_get_keywords.catcode</code>.
     */
    public String getCatcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_get_keywords.catdesc</code>.
     */
    public void setCatdesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_get_keywords.catdesc</code>.
     */
    public String getCatdesc() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PgGetKeywords.PG_GET_KEYWORDS.WORD;
    }

    @Override
    public Field<String> field2() {
        return PgGetKeywords.PG_GET_KEYWORDS.CATCODE;
    }

    @Override
    public Field<String> field3() {
        return PgGetKeywords.PG_GET_KEYWORDS.CATDESC;
    }

    @Override
    public String component1() {
        return getWord();
    }

    @Override
    public String component2() {
        return getCatcode();
    }

    @Override
    public String component3() {
        return getCatdesc();
    }

    @Override
    public String value1() {
        return getWord();
    }

    @Override
    public String value2() {
        return getCatcode();
    }

    @Override
    public String value3() {
        return getCatdesc();
    }

    @Override
    public PgGetKeywordsRecord value1(String value) {
        setWord(value);
        return this;
    }

    @Override
    public PgGetKeywordsRecord value2(String value) {
        setCatcode(value);
        return this;
    }

    @Override
    public PgGetKeywordsRecord value3(String value) {
        setCatdesc(value);
        return this;
    }

    @Override
    public PgGetKeywordsRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgGetKeywordsRecord
     */
    public PgGetKeywordsRecord() {
        super(PgGetKeywords.PG_GET_KEYWORDS);
    }

    /**
     * Create a detached, initialised PgGetKeywordsRecord
     */
    public PgGetKeywordsRecord(String word, String catcode, String catdesc) {
        super(PgGetKeywords.PG_GET_KEYWORDS);

        set(0, word);
        set(1, catcode);
        set(2, catdesc);
    }
}
