/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.records;


import com.example.jooq.demo_jooq.introduction.db.pg_catalog.tables.PgStatUserFunctions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatUserFunctionsRecord extends TableRecordImpl<PgStatUserFunctionsRecord> implements Record6<Long, String, String, Long, Double, Double> {

    private static final long serialVersionUID = 1660864126;

    /**
     * Setter for <code>pg_catalog.pg_stat_user_functions.funcid</code>.
     */
    public void setFuncid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_user_functions.funcid</code>.
     */
    public Long getFuncid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_user_functions.schemaname</code>.
     */
    public void setSchemaname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_user_functions.schemaname</code>.
     */
    public String getSchemaname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_user_functions.funcname</code>.
     */
    public void setFuncname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_user_functions.funcname</code>.
     */
    public String getFuncname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_user_functions.calls</code>.
     */
    public void setCalls(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_user_functions.calls</code>.
     */
    public Long getCalls() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_user_functions.total_time</code>.
     */
    public void setTotalTime(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_user_functions.total_time</code>.
     */
    public Double getTotalTime() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>pg_catalog.pg_stat_user_functions.self_time</code>.
     */
    public void setSelfTime(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>pg_catalog.pg_stat_user_functions.self_time</code>.
     */
    public Double getSelfTime() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, Long, Double, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, Long, Double, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PgStatUserFunctions.PG_STAT_USER_FUNCTIONS.FUNCID;
    }

    @Override
    public Field<String> field2() {
        return PgStatUserFunctions.PG_STAT_USER_FUNCTIONS.SCHEMANAME;
    }

    @Override
    public Field<String> field3() {
        return PgStatUserFunctions.PG_STAT_USER_FUNCTIONS.FUNCNAME;
    }

    @Override
    public Field<Long> field4() {
        return PgStatUserFunctions.PG_STAT_USER_FUNCTIONS.CALLS;
    }

    @Override
    public Field<Double> field5() {
        return PgStatUserFunctions.PG_STAT_USER_FUNCTIONS.TOTAL_TIME;
    }

    @Override
    public Field<Double> field6() {
        return PgStatUserFunctions.PG_STAT_USER_FUNCTIONS.SELF_TIME;
    }

    @Override
    public Long component1() {
        return getFuncid();
    }

    @Override
    public String component2() {
        return getSchemaname();
    }

    @Override
    public String component3() {
        return getFuncname();
    }

    @Override
    public Long component4() {
        return getCalls();
    }

    @Override
    public Double component5() {
        return getTotalTime();
    }

    @Override
    public Double component6() {
        return getSelfTime();
    }

    @Override
    public Long value1() {
        return getFuncid();
    }

    @Override
    public String value2() {
        return getSchemaname();
    }

    @Override
    public String value3() {
        return getFuncname();
    }

    @Override
    public Long value4() {
        return getCalls();
    }

    @Override
    public Double value5() {
        return getTotalTime();
    }

    @Override
    public Double value6() {
        return getSelfTime();
    }

    @Override
    public PgStatUserFunctionsRecord value1(Long value) {
        setFuncid(value);
        return this;
    }

    @Override
    public PgStatUserFunctionsRecord value2(String value) {
        setSchemaname(value);
        return this;
    }

    @Override
    public PgStatUserFunctionsRecord value3(String value) {
        setFuncname(value);
        return this;
    }

    @Override
    public PgStatUserFunctionsRecord value4(Long value) {
        setCalls(value);
        return this;
    }

    @Override
    public PgStatUserFunctionsRecord value5(Double value) {
        setTotalTime(value);
        return this;
    }

    @Override
    public PgStatUserFunctionsRecord value6(Double value) {
        setSelfTime(value);
        return this;
    }

    @Override
    public PgStatUserFunctionsRecord values(Long value1, String value2, String value3, Long value4, Double value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatUserFunctionsRecord
     */
    public PgStatUserFunctionsRecord() {
        super(PgStatUserFunctions.PG_STAT_USER_FUNCTIONS);
    }

    /**
     * Create a detached, initialised PgStatUserFunctionsRecord
     */
    public PgStatUserFunctionsRecord(Long funcid, String schemaname, String funcname, Long calls, Double totalTime, Double selfTime) {
        super(PgStatUserFunctions.PG_STAT_USER_FUNCTIONS);

        set(0, funcid);
        set(1, schemaname);
        set(2, funcname);
        set(3, calls);
        set(4, totalTime);
        set(5, selfTime);
    }
}
